server:
  port: 80

# spring properties
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: ssg4
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# Logging
logging:
  level:
    root: debug
    web: debug
    sql: debug